language: erlang
sudo: false
otp_release:
# Test on all supported releases
   - 18.0
   - 17.5
   - 17.4
   - 17.3
   - 17.1
   - 17.0
   - R16B03-1
   - R16B03
   - R16B02
   - R16B01
   - R16B
   - R15B03
#   - R15B02 #fails
   - R15B01
   - R15B

script:
  - make
  - rebar eunit -v skip_deps=true
  - make test
  - make plt
  - make dialyze
notifications:
  email: false
