language: erlang
sudo: false
otp_release:
# Test on all supported releases & some more
   - 21.1
   - 21.0
   - 20.3
   - 19.3
   - 18.3
   - 17.5

script:
  - make
  - make test
  - make dialyze

notifications:
  email: false
