language: erlang
otp_release:
   - 17.1
   - 17.0
   - R16B03-1
   - R16B02
   - R16B01

script:
  - rebar get-deps
  - rebar compile 
  - rebar eunit -v skip_deps=true
  - make test
  - mkdir plt
  - ./travis-dialyzer.sh
notifications:
  email: false 
