language: erlang
sudo: false
otp_release:
# Test on all supported releases & some more
   - 23.2
   - 22.3
   - 21.3
   - 20.3

script:
  - make
  - make test
  - make dialyze

notifications:
  email: false
